// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package go_micro_srv_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 如下定义的是上边定义的service所用到的参数，这里的结构中都被赋予了初始值
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_55f9003e633dc5e6, []int{0}
}
func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (dst *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(dst, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_55f9003e633dc5e6, []int{1}
}
func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (dst *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(dst, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          []*Consignment `protobuf:"bytes,2,rep,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_55f9003e633dc5e6, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() []*Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

type Getmessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Getmessage) Reset()         { *m = Getmessage{} }
func (m *Getmessage) String() string { return proto.CompactTextString(m) }
func (*Getmessage) ProtoMessage()    {}
func (*Getmessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_consignment_55f9003e633dc5e6, []int{3}
}
func (m *Getmessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Getmessage.Unmarshal(m, b)
}
func (m *Getmessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Getmessage.Marshal(b, m, deterministic)
}
func (dst *Getmessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Getmessage.Merge(dst, src)
}
func (m *Getmessage) XXX_Size() int {
	return xxx_messageInfo_Getmessage.Size(m)
}
func (m *Getmessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Getmessage.DiscardUnknown(m)
}

var xxx_messageInfo_Getmessage proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
	proto.RegisterType((*Getmessage)(nil), "go.micro.srv.consignment.Getmessage")
}

func init() { proto.RegisterFile("consignment.proto", fileDescriptor_consignment_55f9003e633dc5e6) }

var fileDescriptor_consignment_55f9003e633dc5e6 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x24, 0xe9, 0x33, 0x1b, 0x54, 0x54, 0x1f, 0xc0, 0x82, 0x03, 0x51, 0x00, 0xa9, 0xa7, 0x1c,
	0xca, 0x27, 0xe4, 0x50, 0xf5, 0x9a, 0x5e, 0x91, 0xa0, 0x38, 0xab, 0x74, 0x25, 0x62, 0x47, 0xb6,
	0x5b, 0xbe, 0x8d, 0xcf, 0xe0, 0x8f, 0x50, 0x9d, 0x86, 0x5a, 0x42, 0x45, 0xbd, 0x65, 0x76, 0x76,
	0x76, 0x66, 0x14, 0xc3, 0x54, 0x28, 0x69, 0xa8, 0x92, 0x35, 0x4a, 0x9b, 0x35, 0x5a, 0x59, 0xc5,
	0x78, 0xa5, 0xb2, 0x9a, 0x84, 0x56, 0x99, 0xd1, 0xbb, 0xcc, 0xe3, 0xd3, 0xaf, 0x00, 0xe2, 0xfc,
	0x88, 0xd9, 0x04, 0x42, 0x2a, 0x79, 0x90, 0x04, 0xb3, 0xa8, 0x08, 0xa9, 0x64, 0x09, 0xc4, 0x25,
	0x1a, 0xa1, 0xa9, 0xb1, 0xa4, 0x24, 0x0f, 0x1d, 0xe1, 0x8f, 0xd8, 0x35, 0x0c, 0x3f, 0x91, 0xaa,
	0x8d, 0xe5, 0xbd, 0x24, 0x98, 0x0d, 0x8a, 0x03, 0x62, 0x39, 0x80, 0x50, 0xd2, 0xae, 0x49, 0xa2,
	0x36, 0xbc, 0x9f, 0xf4, 0x66, 0xf1, 0xfc, 0x21, 0x3b, 0x15, 0x24, 0xcb, 0xbb, 0xdd, 0xc2, 0x93,
	0xb1, 0x3b, 0x88, 0x76, 0x68, 0x0c, 0x7e, 0xbc, 0x52, 0xc9, 0x07, 0xce, 0x7c, 0xdc, 0x0e, 0x96,
	0x65, 0x5a, 0x43, 0xf4, 0xab, 0xfa, 0x13, 0xfc, 0x1e, 0x62, 0xb1, 0x35, 0x56, 0xd5, 0xa8, 0xf7,
	0xda, 0x36, 0x38, 0x74, 0xa3, 0x65, 0xb9, 0xcf, 0xad, 0x34, 0x55, 0x24, 0x5d, 0xee, 0xa8, 0x38,
	0x20, 0x76, 0x03, 0xa3, 0xad, 0x69, 0x45, 0xfd, 0x96, 0xd8, 0x43, 0x67, 0x37, 0x2e, 0xd0, 0x34,
	0x4a, 0x1a, 0x64, 0x1c, 0x46, 0x42, 0xe3, 0xda, 0x62, 0x6b, 0x39, 0x2e, 0x3a, 0xc8, 0x16, 0x10,
	0x7b, 0xb5, 0x78, 0xe8, 0x7a, 0x3f, 0xfd, 0xdb, 0xbb, 0xfb, 0x2e, 0x7c, 0x65, 0x7a, 0x09, 0xb0,
	0x40, 0x5b, 0xa3, 0x31, 0xeb, 0x0a, 0xe7, 0xdf, 0x01, 0x5c, 0xad, 0x36, 0xd4, 0x34, 0x24, 0xab,
	0x15, 0xea, 0x1d, 0x09, 0x64, 0x6f, 0x30, 0xcd, 0x9d, 0xab, 0xff, 0x03, 0xcf, 0xb3, 0xba, 0x4d,
	0x4f, 0xaf, 0x75, 0x25, 0xd3, 0x0b, 0xf6, 0x02, 0x93, 0x05, 0x5a, 0xff, 0xfc, 0xe3, 0x69, 0xdd,
	0x31, 0xed, 0x79, 0xd7, 0xdf, 0x87, 0xee, 0x71, 0x3e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0xa5, 0xcc, 0x9d, 0xb1, 0x02, 0x00, 0x00,
}
