// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel.proto

package go_micro_srv_vessel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capicity             int32    `protobuf:"varint,2,opt,name=capicity,proto3" json:"capicity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Availanle            bool     `protobuf:"varint,5,opt,name=availanle,proto3" json:"availanle,omitempty"`
	OwerId               string   `protobuf:"bytes,6,opt,name=ower_id,json=owerId,proto3" json:"ower_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_vessel_9615599325f48eb9, []int{0}
}
func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (dst *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(dst, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapicity() int32 {
	if m != nil {
		return m.Capicity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailanle() bool {
	if m != nil {
		return m.Availanle
	}
	return false
}

func (m *Vessel) GetOwerId() string {
	if m != nil {
		return m.OwerId
	}
	return ""
}

type Specification struct {
	Capicity             int32    `protobuf:"varint,1,opt,name=capicity,proto3" json:"capicity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_vessel_9615599325f48eb9, []int{1}
}
func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (dst *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(dst, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapicity() int32 {
	if m != nil {
		return m.Capicity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_vessel_9615599325f48eb9, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

func init() { proto.RegisterFile("vessel.proto", fileDescriptor_vessel_9615599325f48eb9) }

var fileDescriptor_vessel_9615599325f48eb9 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x75, 0x0b, 0x14, 0x18, 0xc5, 0xc3, 0x78, 0x70, 0x83, 0x92, 0x34, 0x3d, 0x71, 0xda, 0x03,
	0xc4, 0x0f, 0xf0, 0x62, 0xa2, 0xc7, 0x62, 0xf4, 0x48, 0x96, 0xed, 0x88, 0x93, 0xb4, 0xdd, 0xa6,
	0xdb, 0x14, 0xfc, 0x19, 0xbf, 0xd5, 0xb8, 0x15, 0x0d, 0xa6, 0xd1, 0xdb, 0xec, 0x9b, 0x37, 0x2f,
	0xef, 0xbd, 0x85, 0xb3, 0x86, 0x9c, 0xa3, 0x4c, 0x95, 0x95, 0xad, 0x2d, 0x5e, 0x6c, 0xad, 0xca,
	0xd9, 0x54, 0x56, 0xb9, 0xaa, 0x51, 0xed, 0x2a, 0x7e, 0x17, 0x10, 0x3e, 0xf9, 0x11, 0xcf, 0x21,
	0xe0, 0x54, 0x8a, 0x48, 0xcc, 0xc7, 0x49, 0xc0, 0x29, 0x4e, 0x61, 0x64, 0x74, 0xc9, 0x86, 0xeb,
	0x37, 0x19, 0x44, 0x62, 0x3e, 0x48, 0xbe, 0xdf, 0x38, 0x03, 0xc8, 0xf5, 0x7e, 0xbd, 0x23, 0xde,
	0xbe, 0xd6, 0xb2, 0xe7, 0xb7, 0xe3, 0x5c, 0xef, 0x9f, 0x3d, 0x80, 0x08, 0xfd, 0x42, 0xe7, 0x24,
	0xfb, 0x5e, 0xcc, 0xcf, 0x78, 0x0d, 0x63, 0xdd, 0x68, 0xce, 0x74, 0x91, 0x91, 0x1c, 0x44, 0x62,
	0x3e, 0x4a, 0x7e, 0x00, 0xbc, 0x84, 0xa1, 0xdd, 0x51, 0xb5, 0xe6, 0x54, 0x86, 0xfe, 0x28, 0xfc,
	0x7c, 0xde, 0xa7, 0xf1, 0x03, 0x4c, 0x56, 0x25, 0x19, 0x7e, 0x61, 0xa3, 0x6b, 0xb6, 0xc5, 0x91,
	0x2d, 0xf1, 0xa7, 0xad, 0xe0, 0x97, 0xad, 0xb8, 0x81, 0x51, 0x42, 0xae, 0xb4, 0x85, 0x23, 0x5c,
	0x42, 0xd8, 0x56, 0xe0, 0x45, 0x4e, 0x17, 0x57, 0xaa, 0xa3, 0x1e, 0xd5, 0x56, 0x93, 0x7c, 0x51,
	0xf1, 0x06, 0x86, 0xed, 0xe4, 0x64, 0x10, 0xf5, 0xfe, 0xbb, 0x3a, 0x70, 0x17, 0x04, 0x93, 0x16,
	0x5a, 0x51, 0xd5, 0xb0, 0x21, 0x7c, 0x84, 0xc9, 0x1d, 0x17, 0xe9, 0xad, 0x8f, 0xbf, 0xc9, 0x08,
	0xe3, 0x4e, 0x9d, 0xa3, 0xe0, 0xd3, 0x59, 0x27, 0xe7, 0x10, 0x28, 0x3e, 0xd9, 0x84, 0xfe, 0x9f,
	0x97, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0x8f, 0xe2, 0xed, 0xf7, 0x01, 0x00, 0x00,
}
